name: Push to Cocoapods
on:
  workflow_dispatch:
  release:
    types: [published]
env:
    PODSPEC_FILE: LiveKitClient.podspec
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Validate Podspec
      run: pod lib lint --allow-warnings
    - name: Publish to CocoaPods
      run: pod trunk push ${{ env.PODSPEC_FILE }} --allow-warnings --verbose
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}